(function () {
  "use strict";

  window.CloseoutData = {
    project: {
      id: "UNIT-204",
      name: "Unit 204",
      building: "The Mason · Level 2",
      package: "Closeout package 02",
      handoffTarget: "31 Aug 2026",
      lastVerified: "28 Aug · 4:19 PM",
      coordinator: "Maya Chen",
    },
    lanes: {
      original_scope: {
        label: "Original-scope deficiency",
        short: "Original scope",
        description: "Work or evidence already required by the contracted closeout scope.",
      },
      owner_acceptance: {
        label: "Owner acceptance",
        short: "Owner review",
        description: "Evidence exists, but an owner inspection decision is still required; the demo keeps the item routed and unresolved.",
      },
      possible_change: {
        label: "Possible change order",
        short: "Scope review",
        description: "The record may relate to a post-scope event. Closeout must not assign cost or responsibility.",
      },
    },
    statusLabels: {
      ready: "Accepted",
      unmatched_evidence: "Evidence found",
      stale: "Stale revision",
      scope_review: "Scope review",
      missing: "Missing record",
      owner_review: "Owner review",
    },
    requirements: [
      {
        id: "as-built",
        label: "As-built drawings",
        status: "ready",
        owner: "General contractor",
        ownerInitials: "GC",
        due: "Accepted 27 Aug",
        lane: "original_scope",
        location: "Whole unit",
        criterion: "Approved architectural and MEP as-built set matches installed conditions and carries the current closeout revision.",
        requiredRevision: "Rev 4",
        currentRevision: "Rev 4",
        summary: "Current coordinated set accepted for handoff.",
        evidenceIds: ["ev-asbuilt"],
      },
      {
        id: "o-and-m",
        label: "O&M manual",
        status: "ready",
        owner: "Mechanical",
        ownerInitials: "ME",
        due: "Accepted 27 Aug",
        lane: "original_scope",
        location: "Mechanical closet",
        criterion: "Current operating and maintenance manual includes installed model numbers and startup procedures.",
        requiredRevision: "Issue 1",
        currentRevision: "Issue 1",
        summary: "Installed-equipment schedule and maintenance sequence verified.",
        evidenceIds: ["ev-om"],
      },
      {
        id: "electrical-test",
        label: "Electrical test report",
        status: "ready",
        owner: "Electrical",
        ownerInitials: "EL",
        due: "Accepted 26 Aug",
        lane: "original_scope",
        location: "Panel E-204",
        criterion: "Signed continuity and insulation test report identifies the installed Unit 204 panel and passes all recorded circuits.",
        requiredRevision: "Final",
        currentRevision: "Final",
        summary: "Signed final test report accepted.",
        evidenceIds: ["ev-electrical"],
      },
      {
        id: "plumbing-test",
        label: "Plumbing pressure test",
        status: "ready",
        owner: "Plumbing",
        ownerInitials: "PL",
        due: "Accepted 26 Aug",
        lane: "original_scope",
        location: "Kitchen wet wall",
        criterion: "Final pressure-test record identifies Unit 204, test pressure, hold duration, and passing witness.",
        requiredRevision: "Final",
        currentRevision: "Final",
        summary: "Passing test and witness signature accepted.",
        evidenceIds: ["ev-plumbing"],
      },
      {
        id: "door-hardware",
        label: "Door hardware schedule",
        status: "ready",
        owner: "General contractor",
        ownerInitials: "GC",
        due: "Accepted 25 Aug",
        lane: "original_scope",
        location: "Entry 204",
        criterion: "Installed hardware set matches the approved door schedule and accessibility notes.",
        requiredRevision: "Rev 2",
        currentRevision: "Rev 2",
        summary: "Entry hardware matched to the approved set.",
        evidenceIds: ["ev-door"],
      },
      {
        id: "appliance-startup",
        label: "Appliance startup",
        status: "ready",
        owner: "Kitchen vendor",
        ownerInitials: "KV",
        due: "Accepted 25 Aug",
        lane: "original_scope",
        location: "Kitchen",
        criterion: "Installed appliances have model-specific startup records with no open commissioning faults.",
        requiredRevision: "Final",
        currentRevision: "Final",
        summary: "All installed appliances started without open faults.",
        evidenceIds: ["ev-appliance"],
      },
      {
        id: "lien-release",
        label: "Conditional lien release",
        status: "ready",
        owner: "General contractor",
        ownerInitials: "GC",
        due: "Accepted 24 Aug",
        lane: "original_scope",
        location: "Project record",
        criterion: "Current conditional release covers the billed closeout period and named contracting entity.",
        requiredRevision: "August",
        currentRevision: "August",
        summary: "Current-period conditional release accepted.",
        evidenceIds: ["ev-lien"],
      },
      {
        id: "keys",
        label: "Keys and access handoff",
        status: "ready",
        owner: "Owner",
        ownerInitials: "OW",
        due: "Accepted 24 Aug",
        lane: "owner_acceptance",
        location: "Entry 204",
        criterion: "Key count, access credentials, and recipient acknowledgement match the Unit 204 handoff schedule.",
        requiredRevision: "Final",
        currentRevision: "Final",
        summary: "Owner receipt recorded for all scheduled keys.",
        evidenceIds: ["ev-keys"],
      },
      {
        id: "cleaning",
        label: "Final cleaning",
        status: "ready",
        owner: "General contractor",
        ownerInitials: "GC",
        due: "Accepted 28 Aug",
        lane: "owner_acceptance",
        location: "Whole unit",
        criterion: "Owner walkthrough confirms all rooms are clean, debris-free, and ready for occupancy inspection.",
        requiredRevision: "Walkthrough",
        currentRevision: "Walkthrough",
        summary: "Final walkthrough accepted with no cleaning exception.",
        evidenceIds: ["ev-cleaning"],
      },
      {
        id: "fire-test",
        label: "Fire damper test",
        status: "unmatched_evidence",
        owner: "Mechanical",
        ownerInitials: "ME",
        due: "29 Aug",
        lane: "original_scope",
        location: "Corridor ceiling · FD-204",
        criterion: "A passing functional test must identify damper FD-204, match the installed location, and be the current approved revision.",
        requiredRevision: "Rev 2",
        currentRevision: "Rev 2",
        summary: "A current passing test exists, but it is not linked to this requirement.",
        evidenceIds: ["ev-fire-photo", "ev-fire-report", "ev-fire-plan"],
        recommendation: "Match Rev 2 to FD-204. The location, revision, and passing verdict satisfy the stated criterion.",
      },
      {
        id: "warranty",
        label: "Kitchen equipment warranty",
        status: "stale",
        owner: "Kitchen vendor",
        ownerInitials: "KV",
        due: "30 Aug",
        lane: "original_scope",
        location: "Kitchen package",
        criterion: "Warranty must cover the installed equipment schedule and remain valid through the required owner period.",
        requiredRevision: "Rev 2",
        currentRevision: "Rev 1 · expired",
        summary: "The linked warranty is expired and one revision behind.",
        evidenceIds: ["ev-warranty-r1"],
        recommendation: "Request Rev 2 from the vendor. Do not carry Rev 1 into the handoff package.",
      },
      {
        id: "ceiling-repair",
        label: "Ceiling repair at grid C4",
        status: "scope_review",
        owner: "General contractor",
        ownerInitials: "GC",
        due: "Decision by 30 Aug",
        lane: "possible_change",
        location: "Living room · Grid C4",
        criterion: "Repair disposition must identify whether the condition belongs to original work, owner-directed work, or a separately priced change.",
        requiredRevision: "Scope decision",
        currentRevision: "Unresolved",
        summary: "Photo metadata places the condition after an owner-directed ceiling change.",
        evidenceIds: ["ev-ceiling-photo", "ev-ceiling-plan"],
        recommendation: "Keep this item out of original-scope deficiency totals until scope ownership is decided.",
      },
      {
        id: "training",
        label: "Owner controls training",
        status: "missing",
        owner: "Controls contractor",
        ownerInitials: "CT",
        due: "31 Aug · 10:00 AM",
        lane: "original_scope",
        location: "Unit 204 controls",
        criterion: "Signed attendance must identify the owner representative, installed controls, training date, and instructor.",
        requiredRevision: "Signed record",
        currentRevision: "Missing",
        summary: "Training is scheduled, but no signed attendance record exists.",
        evidenceIds: [],
        recommendation: "Complete the scheduled session and attach signed attendance before handoff.",
      },
      {
        id: "paint",
        label: "Paint touch-up acceptance",
        status: "owner_review",
        owner: "Owner",
        ownerInitials: "OW",
        due: "29 Aug",
        lane: "owner_acceptance",
        location: "Entry wall · Door 204",
        criterion: "Owner visual review must accept the repaired finish under normal room lighting or record a specific rejection.",
        requiredRevision: "Owner decision",
        currentRevision: "Photo 12",
        summary: "The correction is documented; owner acceptance is still open.",
        evidenceIds: ["ev-paint-photo"],
        recommendation: "Route the photo for owner accept, reject with reason, defer, or reopen after inspection.",
      },
    ],
    evidence: [
      { id: "ev-fire-photo", requirementId: "fire-test", type: "photo", label: "Field verification · FD-204", source: "Mechanical QA", captured: "28 Aug · 9:42 AM", revision: "Rev 2", verdict: "Pass", path: "../assets/evidence/fire-damper-test-r2.png", file: "IMG_2048.jpg", hash: "8bc2…28a7" },
      { id: "ev-fire-report", requirementId: "fire-test", type: "document", label: "Functional test report", source: "Northline Mechanical", captured: "28 Aug · 10:06 AM", revision: "Rev 2", verdict: "Pass", file: "FD-204_Test_R2.pdf", hash: "3f11…a208" },
      { id: "ev-fire-plan", requirementId: "fire-test", type: "plan", label: "Plan locator · FD-204", source: "A-204 reflected ceiling plan", captured: "Issued 18 Aug", revision: "Rev 4", verdict: "Location match", file: "A-204_RCP_R4.pdf", hash: "d29c…741e" },
      { id: "ev-warranty-r1", requirementId: "warranty", type: "document", label: "Kitchen equipment warranty", source: "Bell & Finch Kitchens", captured: "12 Jun", revision: "Rev 1", verdict: "Expired", file: "Kitchen_Warranty_R1.pdf", hash: "902a…17c4" },
      { id: "ev-ceiling-photo", requirementId: "ceiling-repair", type: "photo", label: "Ceiling condition after owner change", source: "Field superintendent", captured: "27 Aug · 3:18 PM", revision: "Photo 04", verdict: "Scope unclear", path: "../assets/evidence/ceiling-repair-c4.png", file: "C4_condition_04.jpg", hash: "a04f…c831" },
      { id: "ev-ceiling-plan", requirementId: "ceiling-repair", type: "plan", label: "Plan locator · Grid C4", source: "A-204 reflected ceiling plan", captured: "Issued 18 Aug", revision: "Rev 4", verdict: "Location match", file: "A-204_RCP_R4.pdf", hash: "d29c…741e" },
      { id: "ev-paint-photo", requirementId: "paint", type: "photo", label: "Touch-up after correction", source: "General contractor", captured: "28 Aug · 1:05 PM", revision: "Photo 12", verdict: "Awaiting owner", path: "../assets/evidence/paint-touchup-acceptance.png", file: "Paint_204_12.jpg", hash: "9a72…bc05" },
      { id: "ev-asbuilt", requirementId: "as-built", type: "document", label: "Coordinated as-built set", source: "General contractor", captured: "27 Aug", revision: "Rev 4", verdict: "Accepted", file: "Unit204_AsBuilt_R4.pdf", hash: "c2d1…4018" },
      { id: "ev-om", requirementId: "o-and-m", type: "document", label: "Mechanical O&M manual", source: "Northline Mechanical", captured: "27 Aug", revision: "Issue 1", verdict: "Accepted", file: "Unit204_OM.pdf", hash: "155b…aa90" },
      { id: "ev-electrical", requirementId: "electrical-test", type: "document", label: "Electrical final test", source: "Brightline Electric", captured: "26 Aug", revision: "Final", verdict: "Accepted", file: "E204_Final_Test.pdf", hash: "76da…f312" },
      { id: "ev-plumbing", requirementId: "plumbing-test", type: "document", label: "Pressure test witness", source: "Apex Plumbing", captured: "26 Aug", revision: "Final", verdict: "Accepted", file: "P204_Pressure.pdf", hash: "81b0…73d9" },
      { id: "ev-door", requirementId: "door-hardware", type: "document", label: "Door 204 hardware set", source: "General contractor", captured: "25 Aug", revision: "Rev 2", verdict: "Accepted", file: "Door204_Hardware_R2.pdf", hash: "3240…4f19" },
      { id: "ev-appliance", requirementId: "appliance-startup", type: "document", label: "Appliance startup record", source: "Kitchen vendor", captured: "25 Aug", revision: "Final", verdict: "Accepted", file: "Unit204_Startups.pdf", hash: "a75b…9901" },
      { id: "ev-lien", requirementId: "lien-release", type: "document", label: "Conditional lien release", source: "General contractor", captured: "24 Aug", revision: "August", verdict: "Accepted", file: "GC_Conditional_Aug.pdf", hash: "bd72…248e" },
      { id: "ev-keys", requirementId: "keys", type: "document", label: "Key receipt", source: "Owner representative", captured: "24 Aug", revision: "Final", verdict: "Accepted", file: "Unit204_Key_Receipt.pdf", hash: "f092…4e5d" },
      { id: "ev-cleaning", requirementId: "cleaning", type: "document", label: "Final cleaning walkthrough", source: "Owner representative", captured: "28 Aug", revision: "Walkthrough", verdict: "Accepted", file: "Unit204_Cleaning.pdf", hash: "d88f…c310" },
    ],
  };
})();
